BASE_URL = "https://hritwick05sas.atlassian.net"
EMAIL = "hritwick.singh05@gmail.com"
API_TOKEN = "ATATT3xFfGF0joIl_FTTJsL_qcPK5O50G4n2W3eLyEXO8dt_9hmMvWTjeCQMTe0O8_nrg3kBUGMOrLj963_s7Ood_FJssrCL0RUDHSgYJyjormEWmWOuSc_8ycAzTPeM6Vvs9QF8SJrlxjRSAnEdMZnBRusF6deJZ5zJ1f6F1znxBjZZTzVaEIM=D1E3B8A3"
PROJECT_KEY = "DPS"
ISSUES_FILE = "C:/Users/hrsing/PycharmProjects/PythonProject/JiraAPI/data/issues.json"
ISSUE_TYPE = "Task"
